# site name
prefixName: yarbei
siteName: 亚北
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /images/avatar.png
url: https://wyabei.com
description:
#cdn: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6
pjax: 1
# 1开启
mathjax: 0

notice: 永远年轻，永远热泪盈眶。
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: {
    技术: {path: /categories/技术/, fa: fa-code },
    生活: {path: /categories/生活/, fa: fa-file-text-o },
    资源: {path: /categories/资源/, fa: fa-cloud-download },
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
#  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
#    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce },
#    番组: {path: /bangumi/, fa: fa-film faa-vertical },
#    歌单: {path: /music/, fa: fa-headphones },
#    图集: {path: /tags/图集/, fa: fa-photo }
#  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
#  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于我: { path: /about/, fa: fa-meetup}


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash:
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /images/cover/(2).jpg.webp }
  - {url: http://github.com/yarbei, title: github, desc: 博主的github, img: /images/cover/(7).jpg.webp }
  - {url: /, title: 亚北, desc: , img: /images/cover/(6).jpg.webp}



# your site build time or founded date
siteBuildingTime: 21/03/2021

#social  url, img PC端配置
social:
  github: {url: http://github.com/yarbei, img: /images/contact/github.png}
  sina: {url: https://weibo.com/u/5710444168, img: /images/contact/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=428825578, img: /images/contact/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/chang-ya-nan-65, img: /images/contact/zhihu.png}
  email: { url: mailto:949883887@qq.com, img: /images/contact/email.svg}
  wechat: {url: /#, qrcode: /images/contact/wechatcode.png, img: /images/contact/wechat.png}
#  wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /images/contact/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/yarbei, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/5710444168, fa: fa-weibo, color: dd4b39}
  qq: {url: http://sighttp.qq.com/authd?IDKEY=aded95e409d126458a906c800bffdb6afa5941f01dab3fd0, fa: fa-qq, color: 25c6fe}

# 赞赏
donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer:
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
#valine: true
#v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
#v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

